config/routes.rb
Rails.application.routes.draw do
    
 
    
  devise_for :admins, controllers:{
      
      session:'admins/sessions'
       }
    
    
  devise_for :users, controllers:{
      
      session:'users/sessions'
       }
    
  get 'order_details/new'

  get 'order_details/show'

  get 'order_details/destroy'

  get 'payment/send'

  get 'payment/receive'

  resources :posts do
    resources :comments
  end 
    

  
    
    root 'posts#index'

 
   get '/gonzalez', to: 'posts#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
has_many :comments, dependent: :destroy
  belongs_to:user
    
    validates_presence_of :title
    validates_presence_of :body
    validates_length_of   :body,:in=> 10..400, :message => "body no valido" 
    

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

    
    
    
  # GET /posts
  # GET /posts.json
  def index
      if user_signed_in?
          
         @posts = current_user.posts
         else 
          
         @posts = Post.all
          
      end 
      
   
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
   if user_signed_in?
      @post = Post.new(post_params)
      @post.user_id=current_user.id
       else
       @post.title
       @post.body
        @post.user_id=current_user.id
       end
       
    respond_to do |format|
      if @post.save
       flash[:success] ="se logro postear"
          format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
          flash[:alert] ="no logro postear"
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_alien.html.erb
<nav class= "top-bar" data-topbar role="navegation">
<ul class="title-area">
<li class="name">
<h1><a href="">Post</a></h1>
</li>
</ul>
<section class="top-bar-section">
<ul >
<li class="has-dropdown not-click"><a href="">menu</a>
  <ul class="dropdown">
        <li class="parent-link show-for-small-only"><a class="parent-link js-generated" href="#">kkkkkkkk</a></li>
        <li class="title back js-generated"><h5><%= link_to 'Back', posts_path %></h5></li>
         
      
      <% if admin_signed_in?%>
        <li><%= link_to 'Ver',controller:'/posts',action:'index'%></li>
     
      <%else%>
        <li><%= link_to 'Ver',controller:'/posts',action:'index'%></li>
      

        <li><%= link_to 'Nuevo',controller:'/posts',action:'new'%></li>
       <li ><%=link_to"Logout",destroy_admin_session_path,method: :delete,:class=>'navbar-link'%></li>
      <%end%>
    
   </ul>    
</li>
       <li class= "divider"></li>
</ul>
    
    <ul class="right">
    
    <p class="=navbar-text pull-right">
        
        <% if user_signed_in?%>
       
        
        <font color="white">Logged in as  <strong><%=current_user.email%></strong> </font>
       
        
        <li >
        <%=link_to 'Edit profile',edit_user_registration_path, :class=>'navbar-link'%></li> 
       
            <li ><%=link_to"Logout",destroy_user_session_path,method: :delete,:class=>'navbar-link'%></li>
       
        
        
        <%else%>
        
        <% if admin_signed_in?%>
        <font color="white">  Logged in as <strong><%=current_admin.email%></strong></font>
            <li ><%=link_to 'Edit profile',edit_admin_registration_path, :class=>'navbar-link'%></li> 
            <li ><%=link_to"Logout",destroy_admin_session_path,method: :delete,:class=>'navbar-link'%></li>
        <%else%>
        
        
        
        <li><%=link_to "Sing up", new_user_registration_path,:class=>'navbar-link'%> </li>
       <li>  <%=link_to "Login", new_user_session_path,:class=>'navbar-link'%></li>
         <li>  <%=link_to "Login_admin", new_admin_session_path,:class=>'navbar-link'%></li>
         <%end%>
    <%end%>
        
    
    </p>
    </ul>
    

    
    
    
    
</section>
    
    
    
    
</nav> 

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 <section class="row">
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title ,:class=> "validate[required]" %>
  </div>
  <div class="field">
      
    <%= f.label :body %><br>
    <%= f.text_area :body,:class=> "validate[required]"  %>
      <section class="row">

          <div class="small-4 columns">
  <div class="actions">
    <%= f.submit 'Aceptar',:class =>'button small' %>
  </div>
          </div>
</div>
</section>
</section>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<section class="row">
    
    
    <div class="small-6 columns">
        <h1>    Listing Posts</h1>
    </div>
        </section>

<section class="row">
    <%if !admin_signed_in? && !user_signed_in? %>
    redi
    <%end%>
    <div class="small-6 columns"> 
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
        <th>correo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
          <td><%=User.find(post.user_id).email%></td>
        <td><% if  post.body %>
          <a href="#" data-reveal-id="post-<%= post.id %>">ver mas</a>
            <div id="post-<%=post.id %>" class="reveal-modal" data-reveal >
        <%=post.body%>
                <a class="close-reveal-modal">x</a>
            </div>
          <% end %>
          </td>
        
          <td><%=link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
         
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %>
          
          
          
          
          
          
          
          </td>
      </tr>
    <% end %>
  </tbody>
</table>
        
       
       
       
        <%if !admin_signed_in? %>
            <%= link_to 'New post', new_post_path, :class => 'default button tiny radius'  %>
        <%end%>
            <div class="small-3 columns"> </div>
        </div>
    <br>


    
</section>

app/views/posts/new.html.erb
<body  >
<marquee>
<h1>New Post</h1>
</marquee>
<%= render 'form' %>
<section class="row" >
  <div class="small-4 columns">
    </div>
    <div class="small-4 columns">
    <%= link_to 'Back', posts_path %>
    </div>
     <div class="small-4 columns">
    </div>
</section>
</body>

app/views/posts/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<div id="comments">
<%= render :partial => @post.comments.reverse %>
</div>

<%= form_for([@post, Comment.new], remote: true) do|f| %>

 <p><%= f.label :body, "New Comment" %><br/>
     <%= f.text_area :body %>
 </p>

<p><%= f.submit "Add Comment" %></p>
<% end %>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>